[package]
name = "rustique"
version = "0.1.0"
authors = ["Olivier Bourgain <olivierbourgain02@gmail.com>"]

[dependencies]
time = "0.1.36"
serde= "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.iron]
version = "*"
